
services:
  postgres:
    image: postgres:17
    container_name: cli-login-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cli_login_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: cli-login-app

    depends_on:
      - postgres

    environment:
      DB_HOST: postgres

    stdin_open: true
    tty: true

volumes:
  postgres_data: